const projects = [
  {name:'DENTALUX', repo:'dentalux', kind:'WEB DEVELOPMENT', cover:'dental', tagline:'A brighter digital experience.', description:'A multi-page dental clinic demo: services, doctors, prices, appointments, and responsive interactions.', tech:'NEXT.JS · TYPESCRIPT · TAILWIND', demo:'https://dentalux-sigma.vercel.app/', note:'Portfolio demo. The published forms do not submit appointments.'},
  {name:'ENT MATH', repo:'ENT-MATH', kind:'EDUCATION PLATFORM', cover:'math', tagline:'One step closer to understanding.', description:'A Russian and Kazakh learning platform for school mathematics and ENT preparation, with lessons, practice, diagnostics, and personal learning routes.', tech:'TYPESCRIPT · CLOUDFLARE · D1', demo:'https://ent-math-learning.netabasyn.chatgpt.site/', note:'Published learning platform. Generative AI integration remains in development.'},
  {name:'ZAGA ZAGA', repo:'zaga-zaga', kind:'WEB DESIGN CONCEPT', cover:'zaga', tagline:'A fresh take on the everyday.', description:'An independent beverage website concept, with expressive typography, interactive can compositions, flavor selection, and responsive motion.', tech:'HTML · CSS · JAVASCRIPT', demo:'https://zaga-zaga.vercel.app/', note:'Independent design concept; not an official brand website.'},
  {name:'FLOW', repo:'flow-downloader', kind:'ANDROID APPLICATION', cover:'flow', tagline:'Your videos. Your music. To go.', description:'An Android video and audio downloader with format selection, background downloads, a media library, and English and Russian interfaces.', tech:'KOTLIN · ANDROID', demo:null, note:'Explore the repository for the published APK and release notes.'},
  {name:'DOCMIND', repo:'docmind-telegram', kind:'AI / TELEGRAM BOT', cover:'docmind', tagline:'From documents to answers.', description:'A Telegram assistant for TXT document summaries and questions, with a local demo mode and OpenAI Responses API integration.', tech:'PYTHON · TELEGRAM · OPENAI', demo:null, note:'Source code and setup instructions. No public browser demo.'},
];


const previewFiles={dental:'/assets/previews/dentalux/index.html',zaga:'/assets/previews/zaga/index.html',collab:'/assets/previews/collab/index.html'};
function projectArt(p){
 if(previewFiles[p.cover])return `<div class="preview-scene scene-${p.cover}"><div class="preview-brand">${p.name}<span>${p.tagline}</span></div><div class="preview-browser"><div class="browser-bar"><i></i><i></i><i></i><span>${p.name.toLowerCase().replaceAll(' ','')}.preview</span></div><div class="website-preview"><iframe src="${previewFiles[p.cover]}" title="${p.name} actual interface preview" sandbox="" tabindex="-1" loading="lazy"></iframe></div></div></div>`;
 if(p.cover==='flow')return `<div class="preview-scene scene-flow"><div class="flow-copy"><img src="/assets/flow-icon.svg" alt="Flow application icon"><strong>flow</strong><p>Your media.<br>Your rhythm.</p></div><div class="flow-device" aria-hidden="true"><div class="device-speaker"></div><div class="flow-device-header">flow <span>↓</span></div><div class="flow-album"><span>▶</span><b>Take it<br>with you.</b></div><div class="flow-track"><i>♪</i><span>Your music<small>Ready to go</small></span><b>✓</b></div><div class="flow-track"><i>▶</i><span>Your videos<small>In your library</small></span><b>✓</b></div><div class="device-home"></div></div></div>`;
 if(p.cover==='math')return `<div class="preview-scene scene-math"><div class="math-copy"><span>Математика · ЕНТ</span><strong>ENT<br>MATH<span>.</span></strong><p>Сложное становится понятным.</p></div><div class="math-sheet" aria-hidden="true"><span>Практика / Алгебра</span><strong>y = x²</strong><svg viewBox="0 0 180 130" fill="none"><path d="M15 105H170M90 12V118" stroke="#a5b8a5"/><path d="M26 18Q90 195 154 18" stroke="#355b42" stroke-width="3"/><circle cx="90" cy="106" r="4" fill="#355b42"/></svg><div>Решение найдено <b>✓</b></div></div></div>`;
 return `<div class="preview-scene scene-docmind"><div class="docmind-copy"><span>Document intelligence</span><strong>docmind<span>_</span></strong><p>Less reading.<br>More understanding.</p></div><div class="docmind-paper" aria-hidden="true"><span>TXT</span><i></i><i></i><i></i><i></i></div><div class="docmind-answer" aria-hidden="true"><div><b>✦</b> Document summary</div><i></i><i></i><i></i><span>From documents to answers ↗</span></div></div>`;
}
function projectCard(p,i){return `<article class="project-card card-${i+1}"><a class="project-cover" href="${p.demo || `https://github.com/yessensiv/${p.repo}`}" target="_blank" rel="noopener noreferrer" aria-label="Explore ${p.name}">${projectArt(p)}<span class="project-kind mono">${p.kind}</span></a><div class="project-caption"><h3>${p.name}</h3><a class="project-visit mono" href="${p.demo || `https://github.com/yessensiv/${p.repo}`}" target="_blank" rel="noopener noreferrer">VISIT ↗</a></div></article>`;}
const track=document.querySelector('#project-track');
track.innerHTML=`<svg class="work-wires" aria-hidden="true"><path></path></svg><div class="work-intro"><span class="role-tag">KEEP SCROLLING</span><h2 id="work-title">SELECTED<br> WORK</h2><p>I'm glad you're still here.</p><a class="corner-button" href="/work">EXPLORE MORE</a></div>`+projects.map(projectCard).join('');
function projectButton(p,i){return `<button class="project-choice" data-project="${i}" aria-pressed="${i===0}"><span class="mono">0${i+1}</span><span>${p.name}<small class="mono">${p.kind}</small></span></button>`;}
document.querySelector('#project-list-left').innerHTML=projects.slice(0,3).map(projectButton).join('');
document.querySelector('#project-list-right').innerHTML=projects.slice(3).map((p,i)=>projectButton(p,i+3)).join('');
const mobileProjects=document.createElement('div');mobileProjects.className='mobile-projects';
mobileProjects.innerHTML=projects.map((p,i)=>`<details class="mobile-project" ${i===0?'open':''}><summary><span class="mono">0${i+1}</span><span><strong>${p.name}</strong><small>${p.kind}</small></span></summary><p>${p.description}</p><div class="detail-links"><a href="https://github.com/yessensiv/${p.repo}" target="_blank" rel="noopener noreferrer">VIEW SOURCE ↗</a>${p.demo?`<a href="${p.demo}" target="_blank" rel="noopener noreferrer">VISIT WEBSITE ↗</a>`:''}</div></details>`).join('');
mobileProjects.addEventListener('toggle',event=>{if(event.target.open)mobileProjects.querySelectorAll('details').forEach(detail=>{if(detail!==event.target)detail.open=false;});},true);
document.querySelector('.project-notes').append(mobileProjects);
{
 const gallery=document.createElement('section');gallery.className='all-work';gallery.id='all-work';gallery.innerHTML=`<div class="all-work-heading"><span class="role-tag">PERSONAL WORKS</span><h1>MY WORK</h1></div><div class="all-work-grid">${projects.map(projectCard).join('')}</div>`;document.querySelector('main').prepend(gallery);
}
